G-Node/python-odml

odml/base.py

If one tries to append a section which is name-wise an duplicate an error is raised.
Should solve issue #24

Check for sections with same name

---

odml/dtypes.py
odml/format.py
odml/tools/jsonparser.py
odml/tools/xmlparser.py
odml/value.py
test/test_dtypes.py

A wonderful PR full of red lines.
Removes unused Value fields: checksum, filename, encoder.
Removes supporting functions: checksum calculation, encoder conversion.
Removes support for binary dtypes.
Closes #50.

Remove unused fields

---

odml/tools/xmlparser.py

Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/odML-1.3.dev0-py3.5.egg/odml/terminology.py", line 76, in _load
term = odml.tools.xmlparser.XMLReader(filename=url, ignore_errors=True).fromFile(fp)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/odML-1.3.dev0-py3.5.egg/odml/tools/xmlparser.py", line 163, in fromFile
raise ParserException(e.message)
AttributeError: 'XMLSyntaxError' object has no attribute 'message'

replace e.message by e.msg

---

odml/terminology.py

I suggest replacing e.message by e to avoid the following exception.
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/odML-1.3.dev0-py3.5.egg/odml/terminology.py", line 80, in _load
print(' "%s"' % e.message)
AttributeError: 'ParserException' object has no attribute 'message'

replaced e.message by e in terminology.py

---

odml/value.py

Fixes #79 
To fix this, we can either use the normal ascii characters `...` to append to the string , or encode the whole string using `utf-8`. 
In this PR, I have used the latter approach.

Fix Value representation if string contains a '\n' character

---

odml/section.py
odml/validation.py

- [validation] Fix param in ValidateError call due to AttributeError: 'object has no attribute 'message'.
- [section] Fix raising RuntimeError.

Fix param in ValidateError call & raising RuntimeError.

---

odml/dtypes.py
odml/property.py
test/test_property.py

Changes requested from issue #96 have been implemented.
- Allow conversion to `boolean` DType 
- If the conversion fails, revert the DType to the original DType
- Add Basic tests
Also, the standard Python `bool` cast is used only as a fallback. Initially, the standard values, that usually relate to a boolean value like `"False"`, `True`, `"0"`, etc. have been checked, and cast to the appropriate `bool` value. 
@jgrewe @lzehl  Does this satisfy the requirements of the mentioned issue ?

DType boolean conversion of values

---

odml/property.py
odml/section.py
test/test_property.py
test/test_section.py

Following issue #93 discussions.
- Add optional `parent` attribute to *args of a Property.
- Change `_section` attr to `_parent` in Property.
- Add update about a new children when a parent is provided as *args in Section and Property.
- Add `reference` attribute as optional *args of a Section.
- Add `_reference` attribute to attributes of a Section.
- Add tests to TestProperty class to cover update parent functionality.

Add update of a parent about a new son.

---

.travis.yml
odml/doc.py
odml/format.py
odml/property.py
odml/section.py
odml/tools/xmlparser.py
setup.py

This PR mainly includes some changes to doc, section, property and format modules.
1) add uuids to the model
2) add format.rdf_map for binding namespaces for predicates' creation.
3) some relevant changes to xmlparser.py
4) add rdflib to setup.py and travis.yml

[rdf] Changes to core

---

doc/odml_ontology/root-ontology.ttl
doc/section_subclasses.yaml
odml/tools/rdf_converter.py
test/test_rdf_writer.py

This PR includes:
- Add section subclasses to ontology. Now it is just a prototype, so `section_subclasses` dict will be extended as mentioned in #151.
- Add generic subclass exporter for sections.
Close #146 #147

Add generic subclass exporter

---

odml/tools/version_converter.py

This PR
- Fixes #181 by putting brackets around multiple values (not single values though).
- Fixes #182 where the converter would crash on an empty secondary multiple value.
- Closes #183 by only exporting attributes actually supported by `document`, `section` and `property` and displaying information about any not-exported fields.
- Closes #184 by checking all multiple value attributes like `unit` and `uncertainty` and displaying warnings if information would be potentially lost.
- Closes #185 by exporting `value.filename` to `property.value_origin`.
- Inhibits the export of empty values e.g. when converting a terminology that has `unit` but no actual value.
- Removes the format when opening an XML file to make `pretty_print` available after the conversion.
- Excludes Properties without …

Version converter fixes

---

odml/section.py
odml/tools/odmlparser.py
test/test_parser.py

- Closes #191 and #194.
- Also removes an 'ODML' parser value from the code which no longer exists with the supported parsers.

Parser fixes

---

.travis.yml
odml/__init__.py
odml/fileio.py
odml/info.py
odml/section.py
odml/tools/odmlparser.py
odml/tools/xmlparser.py
setup.py
test/test_parser.py
test/test_samplefile.py

This PR introduces the following changes to the 1.3 branch:
- [Doc format] Provides a package and a document format version number in the new file `info.py`
- [Doc format] All parsers now use the common document format version number.
- [Doc format] When trying to open a file with any of the odml parsers, first the document format version number is checked. If the found version number does not match the supported one, file loading will fail an exception, since this is the oldest format version. If anyone tries to open a newer format, they should first update their odml package and not use this one...
- [Doc saving] An odML document can now only be saved, if the validation does not show any errors. Saving an invalid document will exit while printing all encountered errors.
- [Parser …

[1.3] Version handling, parser fixes, setup update

---

odml/__init__.py
odml/fileio.py
odml/info.py
odml/terminology.py
odml/tools/odmlparser.py
odml/tools/version_converter.py
odml/tools/xmlparser.py
setup.py
test/test_infer_type.py
test/test_samplefile.py

This PR is mainly cherry picking and refactoring of [1.3] PR #197.
It additionally:
- Changes the version number to 1.4.0.
- Fixes a terminology loading decode error when using python 3.
- Refactors `XMLReader.fromString` and `.fromFile` to snake case.

[1.4] Version handling, parser fixes, setup update, fix terminology load

---

.travis.yml
README.rst
setup.py

This adorable PR
- removes the license text from setup.py. The license text interfered with the PyPI process in a way, that the description was not displayed on PyPI. With this setup it works fine.
- osx builds on travis currently take quite some time until they start. Therefore the osx builds are reduced to one until further notice.
Once this PR has been merged and the package tested on testpypi.python.org, we can do the v1.3.3 release on PyPI proper.

Final fixes for release 1.3.3

---

.travis.yml
README.rst
odml/property.py
odml/terminology.py
odml/tools/xmlparser.py
setup.py
test/test_bugs.py

This PR
- removes the license text from setup.py. The license text interfered with the PyPI process in a way, that the description was not displayed on PyPI. With this setup it works fine.
- osx builds on travis currently take quite some time until they start. Therefore the osx builds are reduced to one until further notice.
- resolves #205 and #206 to fix potential broken terminology loading/parsing.
- adds and uses a default terminology repository: http://portal.g-node.org/odml/terminologies/v1.1/terminologies.xml.

[1.4] Small fixes and CI updates

---

odml/dtypes.py
setup.py

This tiny PR fixes
- a bug in `setup.py` which prohibits local install if the dependencies are not already installed.
- closes #222; boolean false values depending on lower case string conversion are now properly converted to False in python 2 as well.

Local install and py2 boolean conversion fix

---

MANIFEST.in
README.rst
odml/dtypes.py
odml/info.json
odml/info.py
odml/tools/dict_parser.py
setup.py
test/resources/invalid_root.xml
test/resources/invalid_version.json
test/resources/invalid_version.xml
test/resources/invalid_version.yaml
test/resources/missing_root.json
test/resources/missing_root.yaml
test/resources/missing_version.json
test/resources/missing_version.xml
test/resources/missing_version.yaml
test/test_dtypes.py
test/test_json_parser.py
test/test_property.py
test/test_xml_parser.py
test/test_yaml_parser.py

This PR 
- fixes installation issues on "clean" systems: The way package information in `info.py` is imported into `setup.py` currently breaks any local install due to dependency issues on clean systems (which do not have dependencies already installed). Therefore the package information is moved to `info.json` and read in by both `info.py` and `setup.py`.
- Updates the `MANIFEST` by removing the obsolete desktop entry and adding the `info.json` file.
- fixes #224 by disallowing values that cannot be interpreted as boolean for a boolean DType.
- Removes the unused `rdflib-jsonld` dependency since 'python setup.py install' breaks on first
install if both `rdflib` and `rdflib-jsonld` are in the requirements for some non-obvious reason.
- Adds basic tests for xml-, json- and yamlparser as a …

Refactor package info handling

---

.travis.yml
odml/property.py
odml/tools/dict_parser.py
odml/tools/dumper.py
resources/install_osx_virtualenv.sh
test/test_property.py
test/test_rdf_writer.py

replacement pr for #236. The following changes have been made:
1. ``prop.value`` returns a copy(!) of the value list. Manipulating this list will not affect the content of the property (fixes #227).
2. implement ``prop.append``, ``prop.extend`` methods. The first only for single convertible values, the latter for lists of such as well as other properties. (fixes #223)
3. Implement the ``__setitem__`` method for direct value manipulation. Property more or less behaves like a list. Passed values are checked for converability.
4. Implement ``prop.merge`` method. This will sync all but the dependency and dependencyValue attributes. ValueErrors are raised, if information is set in both properties but are in conflict. (fixes #221)
5. add some docstrings
6. some tests

change value related behaviors

---

.gitignore
odml/terminology.py
odml/tools/__init__.py
odml/tools/version_converter.py
test/resources/local_repository_file_v1.0.xml
test/resources/local_repository_file_v1.1.xml
test/test_version_converter.py

This PR refactors the odML version converter.
- Adds a conversion log for info and warning messages to the converter class. Closes #234.
- Includes the conversion of `dtype` and `dependency_value` on property level which was not supported so far.
- Introduces the conversion of JSON and YAML v1.0 files in addition to XML, which remains the default conversion type. Closes #218.
- Changes the main conversion method from `convert_odml_file()` to `convert()`. The conversion method now returns a unicode string that is immediately consumable by the `xmlparser` instead of an lxml ElementTree. Closes #231.
- Handles `repository` and `include` elements: changes v1.0 odml-terminology urls to their v1.1 counterparts. Closes  #216.
- Adds an `.xml` file extension on file saving if none was provided. …

Refactor the odML v1.0 -> 1.1 version converter

---

odml/doc.py
odml/dtypes.py
odml/tools/dict_parser.py
odml/tools/odmlparser.py
odml/tools/xmlparser.py
test/test_dtypes.py
test/test_infer_type.py
test/test_property.py
test/test_samplefile.py

This pull request 
- Changes the way dtypes handles default values. If a value is `None` or `""`, the defined default value of the corresponding dtype is returned. Closes #228.
- This update also fixes load errors on Empty and None boolean and datetime related values. Closes #245.
- Use only `date/time_get`: Removing all `x_set` functions for time, date and datetime and using the corresponding `x_get` functions instead analogous to all other dtype functions. This also fixes, that the `date_set` was redirected to `time_set`.
- Introduces and uses constants for the format of date, time and datetime in dtypes. This also has the benefit of exposing the required formats to the outside.
It also
- Replaces all `type()` checks with `isinstance()`. Closes #226.
- Fixes saving of odML style tuples …

dtypes refactoring and various bugfixes!

---

test/test_dtypes_integration.py

The added tests check saving and proper loading and parsing of the supported odML dtypes with all three supported parsers.

Dtypes integration tests

---

odml/property.py
test/test_property.py
test/test_property_integration.py

This PR adds more Property tests and adds the following tweaks:
- Avoids an error on append, if the dtype of the Property was not set. Closes #266.
- Makes sure that `Property.append` exits on empty values but accepts `0` and `False`.
- Sets `uncertainty` to `None` if an empty string is passed to it.
- Refactors the Property `value` test and adds `extend`, `append` and `simple_attributes` tests.

Property tests and tweaks

---

odml/base.py
odml/property.py
odml/section.py
test/test_property.py
test/test_section.py

This PR
- Refactors `SmartList` to always only contain `Sections` or `Properties` and adds `setitem` with a check to make sure only the supported object type can be added to an existing list. Closes #272.
- Moves `Property.merge()` attribute checks to its own method `Property.merge_check()`, since its also required during `Section.merge()` when merging child Properties of a Section.
- Adds a `Section.merge_check()` method which validates whether a Section including all its subsections and subproperties can properly be merged. A `ValueError` is raised if any potential merge problem arises. This is necessary since a recursive Section merge cannot be easily rolled back once begun.
- A Section merge imports `reference` and `definition` from the source Section, if they were `None` in the …

Refactor Property and Section merge

---

odml/base.py
odml/doc.py
odml/property.py
odml/section.py
odml/tools/odmlparser.py

This PR flattens the odml class hierarchy since it is unlikely that we will support differing odML class implementations any time soon.
- removing `base._baseobj` class, making `BaseObject` the root odML class.
- removing `doc.Document` class, making `BaseDocument` the only odML document class.
- removing `section.Section` class, making `BaseSection` the only odML section class.
- removing `property.Property` class making `BaseProperty` the only odML property class.
The PR also
- reorders various magic methods to the top of their respective class to easier spot where custom magic methods are defined.
- renames `baseobject` and `sectionable` to `BaseObject` and `Sectionable` respectively.
- removes outdated `odmlparser.is_valid_attribute` method which had already previously copied to the …

Flatten odml class hierarchy

---

odml/format.py
odml/property.py
odml/section.py
odml/tools/odmlparser.py
odml/tools/xmlparser.py
test/test_property.py
test/test_section.py

This PR mainly refactors how required attributes of `Section` and `Property` are handled.
- Required attributes of odML entities in `format.py` where changed: `Section.name`, `Section.type` and `Property.name` are the only attributes set to be required for their respective odML entites. Closes #240.
- `Section` and `Property` `name` can now be `None` on initialization. If this is the case, the entities' `id` values is used as `name` value.
- Hardcoded checks for existing `name` attributes in the XML Parser are removed. Only attributes set as required in `format` are now used to check for missing required odML entity attributes. Close #241.
- The `name` attribute of a `Section` or a `Property` can now only be rewritten, if there is no sibling with the same name on the same hierarchical …

Refactor required attribute handling

---

odml/tools/dict_parser.py
odml/tools/parser_utils.py
odml/tools/xmlparser.py

This PR adds a custom InvalidVersion exception and uses it in xml and dict parser when an old odML format version is read in. This is required to differentiate this case from other ParserExceptions e.g. when trying to load an odML file via odml-ui.

Add custom InvalidVersion exception

---

.travis.yml
appveyor.yml
doc/odml_ontology/root-ontology.ttl
odml/tools/rdf_converter.py
test/resources/version_conversion.yaml
test/resources/version_conversion_int.yaml
test/test_parser_odml.py
test/test_rdf_writer.py

Currently the RDF class `Bag` is used to store `odml.Property` values. To note, that the order of the values is important, this PR switches `Bag` to the RDF container class `Seq` which implies order. Since `rdflib` currently does not support proper `Seq` behaviour with RDF `li` items, for now the index of the value items will be manually written as RDF properties, which `rdflib` supports when reading the file in again.
Any suggestions to solve this issue differently are welcome.
This PR further
- adds python versions to the CI builds.
- updates yaml testfiles to partially address #291.

[RDF] 'Bag' to 'Seq'

---

.travis.yml
odml/tools/version_converter.py
odml/tools/xmlparser.py
test/test_version_converter.py

- This PR closes #288, fixing that an XML file with an UTF-8 encoding file header was not being properly parsed by the VersionConverter XML parser.
- The PR also addresses issue #295 which occurred in the xmlparser: When reading a single string value from csv which contains commata, it now remains a single value and is not split up at each comma.
Further, any leading or trailing whitespaces are removed from any string values when it is written to
csv. Along the same lines, multiple values that are saved to file via the `version_converter` do not contain leading whitespaces any longer.
- The travis build for macOS with python 3.5 was removed, since the pyyaml dependency was failing for python 3.5.

Fix VersionConverter encoding issue

---

odml/doc.py
odml/tools/odmlparser.py
odml/tools/rdf_converter.py
odml/tools/version_converter.py
odml/tools/xmlparser.py
test/test_parser_odml.py

When running parsers and converters with python2 it frequently happened to receive an encoding error while opening a file. Hopefully now encoding and usage of `unicode` is used everywhere where it is needed.
This PR also adds a new private attribute `_origin_file_name` to the `doc` entity. When an odML document is loaded from file, this attribute is now set with the file name from whence the document was loaded. When writing an RDF file from an odML document that features an `_origin_file_name` the value is exported as `odml:hasFileName`.
The PR also makes `xml` the default `ODMLWriter` format when writing a document to RDF since the `xml` format of RDF is still the format with the broadest acceptance.

Conversion encoding

---

odml/info.json
odml/scripts/odml_export_rdf.py
odml/scripts/odml_to_rdf.py
setup.py

This PR adds a convenience command line script to the odML package, that searches through a given directory, converts all found odML files to the latest version and exports all odML files to the RDF format. The conversion is focused on converting as many files as possible in mixed repositories, which possibly contain unrelated XML, JSON or YAML or invalid odML files. Therefore all exceptions are ignored, the tool simply prints a report at the end of the conversion to inform about successes and failures.
After pip install, the script can be called by typing `odmlexportrdf [-r] [-o OUT] SEARCHDIR` with the arguments:
```
Arguments:
SEARCHDIR       Directory to search for odML files.
Options:
-o OUT          Output directory. Must exist if specified.
If not specified, output files will be …
```

odML to RDF export script

---

odml/tools/version_converter.py

The VersionConverter dealt with an edge case of XML test files with opening `<B0>` tags that were missing their closing tag rendering them broken. Catching this one edge case circumvented opening XML files via `lxml`, leaving the resulting document open to various encoding problems.
This PR drops support to resolve the specific tag edge case in favour of properly opening XML files via `lxml`.

Drop VersionConverter broken XML file support

---

CHANGELOG.md
odml/base.py
odml/property.py
odml/section.py
odml/tools/odmlparser.py
odml/validation.py
test/test_property.py
test/test_section.py
test/test_validation.py

This PR closes #258 and #259.
When cloning a `Section` or a `Property` by default the id of any object is changed to a new UUID. The cloning methods now feature a new `keep_id` attribute. If set to `True`, the cloned object and any cloned children retain their original id. This is meant to enable the creation of exact copies of Section-Property trees in different documents.
With the introduction of new validation checks for identical ids within a document in PR #303 a document cannot be saved, if a cloned object with a kept id is added ensuring that ids remain unique within a document.

Clone id handling changes

---

.gitignore
odml/base.py
odml/property.py
odml/section.py
test/test_doc.py
test/test_section.py

This PR aims to make working with odml and the odml part of nixpy more similar. 
The `create_section` method is added to `Document` and `Section` and the `create_property` method to `Section`. The `props` alias attribute of `properties` is added to `Section` to close #299.
Let me know if I missed any nixpy attribute that should be ported to odml as well and whether we should unify `__repr__` of `Section` and `Property` as well, since they are currently different.
See also #308 for completeness of this topic.

Harmonize attribute naming with nixpy

---

odml/fileio.py
odml/tools/dict_parser.py
odml/tools/odmlparser.py
odml/tools/xmlparser.py

This small PR resolves #305 by adding a 'show_warnings' flag to all load methods. The flag is 'True' by default and toggles whether warning messages are printed to the command line when loading an odML document.

Toggle warning messages on load

---

CHANGELOG.md
doc/tutorial.rst
odml/base.py
odml/doc.py
odml/format.py
odml/property.py
odml/section.py
odml/tools/dict_parser.py
odml/tools/dumper.py
odml/tools/xmlparser.py
odml/validation.py
test/test_dtypes_integration.py
test/test_dumper.py
test/test_infer_type.py
test/test_property.py
test/test_samplefile.py
test/test_section.py
test/test_version_converter_integration.py

This PR aims to make working with odml and the odml part of nixpy more similar and closes #308 and #309.
- `__repr__` of both `Section` and `Property` are now similar to the nixpy style.
- `Section.__repr__` also features the immediate child `Property` count next to the child `Section` count.
- The nixpy style `pprint` methods have been added to both `Section` and `Property`.
To make working with odML and [nixpy](https://github.com/G-Node/nixpy) more similar, the `Property.value` attribute has been marked deprecated and the `Property.values` attribute has been added. This is a significant change, since `Property` attributes are serialized to and from a file when saving / loading to any of the supported file formats.
Since I did not want any changes in the file format itself, …

nixpy style values and printing

---

CONTRIBUTING.md
README.md
setup.py

Add a few words about governance to the CONTRIBUTING guideline

---

.travis.yml
CONTRIBUTING.md
README.md
setup.py

This PR
- upgrades the pyyaml dependency to the non-breaking beta version 4.2b4. Once a stable version is available, the dependencies should be updated again. Closes #291.
- removes the Python 3.4 build from the travis build list, since 3.4 will no longer be supported after March 2019.
- changes the Appveyor badge in `README` to the "G-Node" project build.
- adds minor typo fixes and comments to the `CONTRIBUTING` file.

pyyaml dependency upgrade

---

odml/doc.py
odml/dtypes.py
odml/property.py
odml/tools/version_converter.py
test/test_property.py
test/test_version_converter.py

With this pull request:
- IDs are automatically added when converting from odML version 1 to odMl version 1.1 for document, section and property elements.
- A document.pprint method is added showing document information and section/property tree. Closes #319 
- Property can be set as int with value = 0. Fixing #314 
- Appending and Extending of property values of dtypes "person", "url" and "text" is possible. Fixes #318.

Automatically Add IDs At Verison Conversion

---

odml/scripts/odml_view.py
setup.py

Currently most web browsers no longer support viewing local files, that include further local files; see [here](https://developer.mozilla.org/en-US/docs/Archive/Misc_top_level/Same-origin_policy_for_file:_URIs) for additional details.
odML XML files can be nicely rendered by stylesheets, but with the changes described above, this no longer works as smoothly as it did before on a local machine.
This PR therefore introduces another CLI script, `odmlview`, that starts up a local webserver. This webserver is able to properly serve odML XML files from a local directory and render them correctly, if the appropriate stylesheets are present in the same directory.
The CLI script provides an option (`--fetch`) to download the most commonly used xsl stylesheet, `odmlTerms.xsl` from …

CLI script to locally view odml files via webbrowser

---

odml/tools/format_converter.py
odml/tools/rdf_converter.py
odml/tools/utils.py
test/test_rdf_writer.py

With this pull request:
- The default format for RDFWriter is set to turtle. Closes #214 
- The RDF Writer checks for a given file extension within the RDF document name, if accidentally given there. Closes #213 
- The RDF Writer throws a ValueError, if an unsupported RDF format is given (with respective test). Closes #215

RDF Writer Formats

---

odml/scripts/odml_view.py

The stylesheets to display an odML file have changed on the main hosting site.
The changes have been added to the small servlet script to display local odML files in the browser.

[scripts/odmlview] Fix changed stylesheets

---

MANIFEST.in
odml/doc.py
odml/tools/rdf_converter.py
odml/tools/xmlparser.py
test/resources/ignore_errors.xml
test/test_parser_xml.py

This pull request
- fixes the XML reader "ignor errors" mode, if handling entity attributes fails. Closes #276.
- properly fixes the RDF Writer installation. Closes #212.
- fixes wrong indentation in doc.py pprint().

RDF Converter, XML Reader Updates

---

doc/example_odMLs/THGTTG.odml
doc/example_odMLs/sample_odml.odml
doc/example_odMLs/sample_odml.rdf
doc/example_odMLs/thgttg.py
doc/example_rdfs/example_data/drosophila_2.ttl
doc/example_rdfs/example_data/drosophila_4.ttl
doc/example_rdfs/example_data/drosophila_8.ttl
doc/odml_ontology/root-ontology.ttl
doc/tutorial.rst
docs/data_model.md
docs/index.md
odml/templates.py
odml/terminology.py
test/resources/version_conversion_int.json
test/resources/version_conversion_int.xml
test/resources/version_conversion_int.yaml
test/test_version_converter_integration.py

Since we now not only feature odML terminologies but also odML templates, this PR adds first support for importing and working with odML templates:
- updates all terminology URLs to the new terminology deployment.
- adds a templates file to the library that gives access to import and clone template functions;
default URL is `templates.g-node.org`.
- updates the documentation and adds new documentation where required.
In the long run functions common to `templates` and `terminologies` should be combined but for the current first implementation they will still be kept separate.

Add odML templates support

---

.travis.yml
CHANGELOG.md
README.md
appveyor.yml
doc/tools.rst
docs/index.md
odml/info.json
odml/scripts/odml_convert.py
setup.py

This PR prepares for the release of version 1.4.3. It
- updates the release number, copyright date and the classifiers in `info.json`.
- adds all changes since v1.4.2 to the `CHANGELOG`.
- restructures the `README` file and adds a badge for easy access to readthedocs.
- updates the travis build matrix to include Python 3.7 and 3.8 builds and the appveyor build matrix to include Python 3.7 builds.
- the CLI script `odmlconversion` is renamed to `odmlconvert`. All documentation is updated, the script is still available under its previous name `odmlconversion` with a deprecation notice.

Preparation for version 1.4.3 release

---

odml/tools/odmlparser.py

Fixes #343 .
Selecting a PyYaml loader instead of the default loader. The default loader fails on Python 3.8

Selected yaml.Loader while reading odml documents

---

odml/property.py
odml/section.py
test/test_property.py
test/test_section.py

This pull request
- Introduces a leaf export feature for sections and properties. Closes #340 
- Renders error messages regarding dtype format more precise. Closes #341

Leaf Export and Property Handling

---

.travis.yml
CHANGELOG.md
doc/conf.py
odml/info.json
setup.py

This PR prepares for the release of version 1.4.4. It
- updates the release number, copyright date and the classifiers in `info.json`. It also removes the `Python 2.7` classifier since Python 2 has reached end of life and future versions of odML will drop Python 2 compatibility.
- adds all changes since v1.4.3 to the `CHANGELOG`.
- removes the dependency fix on pyyaml version 4.2b4. The problems with pyyaml have been solved with PR #344.

Preparation for version 1.4.4 release

---

odml/base.py
odml/section.py

Import ABC from collections.abc instead of collections for Python 3.9 compatibility.

---

MANIFEST.in
odml/__init__.py
odml/dtypes.py
odml/property.py
odml/tools/converters/version_converter.py
odml/tools/dict_parser.py
odml/tools/parser_utils.py
odml/tools/rdf_converter.py
odml/tools/xmlparser.py
test/test_dtypes.py
test/test_dtypes_integration.py
test/test_parser_yaml.py
test/test_rdf_writer.py

This PR introduces a couple of fixes and updates:
- cleans up all usages of the unsafe `yaml.load` calls and replaces them with `yaml.save_load`. This also prepares for Python 3.9 compatibility.
- refactors dtype tests that are still using `assertRegexpMatches` which is supported in Python 2 but not in Python 3.9 and adds `assertRegex` instead which is supported in Python 3.2+ but not in Python 2.
- adds a `warning` module deprecation warning if the odml library is used with a Python version < 3.6.
- refactors odml style tuple handling and closes #250,  #353 and #354. Now lists of odml style tuples are properly saved to file and can be loaded again. If an invalid format is used to add an odml style tuple, more detailed exception messages are available. Also adds more odml style tuples …

Minor fixes and cleanup

---

odml/rdf/query_creator.py
test/test_rdf_reader.py

This PR
- adds a test for the RDF Reader. Closes #211 
- adds odML namespace definition import from formats for the files in odml/rdf. Closes #345

RDF Reader Test and Namespace

---

odml/format.py
odml/info.json
odml/property.py
odml/tools/dict_parser.py
odml/tools/xmlparser.py
odml/validation.py
test/test_dumper.py
test/test_property.py
test/test_property_integration.py
test/test_validation.py
test/test_validation_integration.py

This PR is supposed to show by example how a cardinality implementation (see issue #361) could look like and provides more grounds for discussion.
The current PR adds the basic cardinality implementation for Property.values. It provides
- an update in `format`.
- an update in the `Property.__init__`.
- `val_cardinality` accessor methods.
- Parser methods to read the cardinality after saving to file for all three supported file formats.
- Cardinality validation example.
Tests will still be pushed to this PR.
The PR should serve as a basis for discussion before the cardinality feature can be extended to sections and properties as well.

Property values cardinality implementation

---

odml/base.py
odml/property.py
odml/section.py
odml/validation.py
test/test_doc.py
test/test_section.py
test/test_validation.py

With recent updates the library now respects and enforces `Section.type` as a required attribute and allows save only with documents where this requirement is satisfied.
To allow backwards file compatibility and ease usage, `Section.type` is by default set to the string `n.s.` (not specified), which means files where no section type had been specified can be loaded and saved, but will contain `n.s.` as value for all `Sections.types` that where previously not specified.
Further the validation run before a document can be saved will issue a warning, if a `Section.type` with value `n.s.` is encountered and will still refuse to save with an error, if an empty `Section.type` is encountered.
Further changes in this PR:
- the `base.Sectionable.create_section` method has been updated to conform …

Change in Section type default behavior

---

odml/property.py
odml/util.py
test/test_util.py
test/test_validation_integration.py

This PR is a preparation for the introduction of Section-section and Section-property cardinality features to keep PRs at a size that is still convenient to review.
The PR introduces
- a generalization of the cardinality function for later reuse by different cardinalities
- catches some edge cases in the core cardinality function
- filters the validation warnings when checking for cardinality violations to display only warning messages specific to the validated object and not from connected objects as well.
- adds and updates tests where required

General cardinality feature updates

---

odml/format.py
odml/section.py
odml/tools/dict_parser.py
odml/validation.py
test/test_section.py
test/test_section_integration.py
test/test_validation.py

The current PR adds the basic cardinality implementation for Section.properties. It provides
- an update in the Section.__init__.
- prop_cardinality accessor methods.
- a set_properties_cardinality convenience method.
- an update to the tools.dict_parser to properly write and read tuples with yaml.
- and registers a Section properties cardinality validation.
- tests for the implemented features.
The PR refers to issue #361. Another PR providing the missing Section.sections cardinality will follow.

Adding Section properties cardinality

---

odml/format.py
odml/section.py
odml/validation.py
test/test_section.py
test/test_section_integration.py
test/test_validation.py

The current PR adds the basic cardinality implementation for Section.sections. It 
- provides an update in the `Section.__init__`.
- adds `Section.sec_cardinality` accessor methods.
- adds a `Section.set_sections_cardinality` convenience method.
- adds and registers a Section sections cardinality validation.
- provides tests for the implemented features.
The PR refers to issue #361.

Adding Section sections cardinality

---

README.md
doc/tutorial.rst
odml/base.py
odml/doc.py
odml/property.py
odml/section.py
odml/tools/converters/format_converter.py
odml/tools/converters/version_converter.py
odml/tools/odmlparser.py
odml/tools/parser_utils.py
odml/tools/rdf_converter.py
odml/tools/xmlparser.py
test/test_bugs.py
test/test_doc.py
test/test_dtypes.py
test/test_dumper.py
test/test_fileio.py
test/test_find_section.py
test/test_format_converter.py
test/test_infer_type.py
test/test_iterators.py
test/test_property.py
test/test_rdf_reader.py
test/test_rdf_writer.py
test/test_samplefile.py
test/test_section.py
test/test_terminology.py
test/test_validation.py
test/test_version_converter.py

This large PR adds various updates and general cleanups for simplification and PEP8 compliance.
In detail it
- adds getter and setter to the `odml.Document.origin_file_name` attribute. This closes issue #358.
- changes the Exception type in `odml.tools.converters.VersionConverter` to `odml.tools.parser_utils.ParserException`. This closes issue #359.
- adds a new test file `test/test_terminology.py` and adds a test for the `terminology.refresh` method.
- refactors the `odml.Property.export_leaf` method to also include sibling properties in the export.
- updates the README to include links to TravisCI an Coveralls
- updates the tutorial to include descriptions of `pprint` and the added `cardinality` feature and adds a link to the `templates` hosting site.
- introduces PEP8 code fixes to all …

General updates and PEP8 code cleanup

---

odml/format.py
odml/tools/dict_parser.py
odml/tools/odmlparser.py
test/test_parser_json.py
test/test_parser_yaml.py
test/test_terminology.py

The XMLParser.Reader comes with an option to ignore errors when opening a file while notifying the user with all encountered odml format problems, enabling users to fix problematic odml files using the odml library instead of having to directly manipulate the file content.
This option has now been added to the DictParser.Reader as well, also allowing to open and fix problematic odml JSON and YAML files.
The PR
- adds all necessary changes in the DictParser.Reader to enable ignoring errors, collecting warnings and printing corresponding notifications. These changes close issue #367.
- changes the ODMLParser.Reader for JSON and YAML to now ignore_errors by default e.g. when using the `odml.load` function.
- fixes a bug in `format.revmap` where the reverse mapping of an odml attribute would …

Implement ignore_errors for DictParser.Reader

---

README.md
odml/__init__.py
odml/property.py
odml/section.py
odml/tools/converters/version_converter.py
odml/tools/version_converter.py
test/test_doc.py
test/test_doc_integration.py
test/test_dtypes_integration.py
test/test_fileio.py
test/test_format_converter.py
test/test_links.py
test/test_parser_json.py
test/test_parser_odml.py
test/test_parser_xml.py
test/test_parser_yaml.py
test/test_property_integration.py
test/test_samplefile.py
test/test_section_integration.py
test/test_terminology.py
test/test_validation.py
test/test_version_converter.py
test/test_version_converter_integration.py
test/test_xml_writer.py
test/util.py

This PR fixes a couple of minor issues and reorganises the way tests handle temporary and resource files.
- all saved XML odML files now use the same XML header. Closes #339.
- all deprecation warnings now use the `warnings` module.
- the `Property.value` attribute deprecation warnings have been unified. Closes #360.
- a Python 2 deprecation warning for August 2020 has been added. See #387 for details.
- the link to the odML tutorial in the README file now points to readthedocs.
- tests writing temporary files now properly clean up after themselves. Closes #381.
- tests now use a common temporary directory to write files and use a constant for accessing the `test/resources` directory.

Minor issue fixes and test reorganisation

---

odml/doc.py
odml/property.py
odml/section.py
odml/tools/odmlparser.py
odml/validation.py
test/test_validation.py

This PR contains a couple of potentially controversial points and should be discussed here before merging and addresses the issues #377, #378 and #379.
Changes to the Validation class enabling Custom Validation Instances sneaked itself in at an [earlier commit](https://github.com/G-Node/python-odml/commit/f6fefe07298113f2c77cbffe2ddf1a13500eaae0) and should be taken into account when reviewing this PR. Check changes in `Validation.__init__()` and `run_validation` and `register_custom_handler` methods. Sorry for the mixup...
This PR 
- adds a validation_id enum class.
- adds individual validation_ids to each validation to make them identifyable via an ID rather than by their error message.
- adds a validation_id field to the ValidationError as well.
- uses the validation_id when running …

Validation changes

---

CHANGELOG.md
README.md
doc/reference.rst
doc/support-classes.rst
doc/tutorial.rst
odml/property.py
odml/section.py
odml/validation.py
test/test_validation.py

This PR prepares for the release of version 1.5.0.
The package up to the latest commit in this PR has been packaged and uploaded to TestPyPI. All command line scripts as well as dependent packages like odml-ui, nix-odml-converter and odmltools have been successfully tested using the package uploaded to TestPyPI.
The PR itself
- updates the tutorial and adds descriptions for the cardinality feature and the validations.
- adds the validation classes as well as the `TemplateHandler` and `Terminology` class to the class reference.
- updates the CHANGELOG including all changes since the1.4.5 release.
- refactors all cardinality validation usages in Section and Property. Previously the default validation was used, which included ALL registered validations in the run. Now it uses a custom …

Preparation for version 1.5.0 release

---

odml/property.py
test/test_property.py

This PR:
- Allows processing of tuples given as a list instead of a string as well, when setting property values, appending or extending them. Closes #392
- Adds the related tests

List-Style Tuple Integration

---

odml/property.py
test/test_property.py

This PR:
- Enables the reordering of section properties.
- Adds a method to insert a new property.value at a certain index.

Property Reorder & Value Insert

---

.travis.yml
appveyor.yml
odml/tools/rdf_converter.py
setup.py
test/test_rdf_writer.py

This PR closes issue #397 and its sub-issues #394, #395 and #396.
RDF subclasses are now properly added by default to any written RDF document. The RDF document will now also include RDF Subclass definitions in addition to the actual data (see issue #396) to enable Subclass specific queries.
- The RDFWriter features an `rdf_subclass` attribute, to disable subclassing (see issue #394).
- The RDFWriter features a `custom_subclasses` attribute to provide additional subclass mappings in addition to the default one (see issue #395).

RDF Subclassing feature

---

odml/fileio.py
odml/tools/odmlparser.py
test/test_fileio.py
test/test_parser_odml.py

This PR adds the support for `kwargs` in via `odml.save` and `odmlparser.ODMLWriter`.
With this change both access points to writing odml files now also support specified save options:
- saving XML documents with the localstyle option or a custom XSL string.
- saving RDF documents with a different file format than the default XML format.
This PR closes issue #402.

Allow additional keywords in 'odml.save'

---

.travis.yml
CHANGELOG.md
appveyor.yml
odml/dtypes.py
odml/format.py
odml/property.py
odml/scripts/odml_convert.py
odml/scripts/odml_to_rdf.py
odml/templates.py
odml/terminology.py
odml/tools/converters/format_converter.py
odml/tools/converters/version_converter.py
odml/tools/odmlparser.py
odml/tools/rdf_converter.py
odml/tools/xmlparser.py
odml/validation.py
test/test_dtypes.py
test/test_infer_type.py
test/test_samplefile.py
test/test_version_converter.py

Python 2 has reached end of life
- the codebase has been cleaned from Python 2 and Python 3 compatible code.
- all tests now run exclusively on Python 3 versions.

Dropping Python 2 support

---

odml/tools/xmlparser.py
test/test_xml_writer.py

Python encodes with cp1252 per default on Windows, resulting in invalid xml files. As the xml header always states that utf-8 is used, I actually enforced it when opening the file for writing. This fixes problems with parsing the written xml files under Windows operating systems.

Force xml writer to use utf-8 encoding on all operating systems

---

.github/workflows/run-tests.yml
.travis.yml
README.md
requirements-test.txt
setup.py

Travis still accepts jobs, but it is slow and its unsure how long it will be available. Therefore we are migrating to github actions.
The current github actions setup
- runs all available tests in a `[ubuntu, macos, windows]`, Python `[3.6, 3.7, 3.8, 3.9]` matrix.
- runs coveralls separately using Python 3.8.
The PR also 
- fixes a dependency build issue: when installing the package using `python setup.py install` an unstable dependency, a pre-releae of `pyparsing` is installed by default. Setup.py now specifies the latest stable version. This fixes issue #410.
- adds a test requirements file for easy github actions installation.
- switches running tests from the deprecated `python setup.py test` to `pytest`.
- removes Python < 3.4 specific code from `setup.py` which we no longer support. …

Introducing github actions

---

CHANGELOG.md
LICENSE
appveyor.yml
odml/__init__.py
odml/info.json
requirements-test.txt
setup.py

This PR
- pins the RDFlib library version and the test dependent owlrl library version. This is required since major changes were introduced to RDFlib in the 5.0.0->6.0.0 release. Until these breaking changes have been fixed in code, the libraries are pinned to ensure that a pip install of odml does not lead to broken code in the rdf specific parts of the odml library.
- adds a py2.7 and py3.5 deprecation warning to the `setup.py`.
- prepares the library for release 1.5.2: updates in info.json, CHANGELOG and LICENSE.
- adds Python 3.9 to appveyor
- deactivates two tests for appveyor builds only: The tests `test_handle_include` and `test_handle_repository` from the `TestVersionConverter` class consistently fail with an SSL certification failure on the appveyor Windows builds. Upgrading the …

Pin RDFlib library, release 1.5.2

---

.github/workflows/run-tests.yml
CHANGELOG.md
README.md
appveyor.yml
doc/support-classes.rst
doc/tutorial.rst
odml/__init__.py
odml/info.json
odml/tools/rdf_converter.py
requirements-test.txt
scripts/release_tests/run_pypi_odml.sh
scripts/release_tests/run_test_local_odml.sh
scripts/release_tests/run_test_matrix.sh
scripts/release_tests/run_test_pypi_nixodmlconverter.sh
scripts/release_tests/run_test_pypi_odml.sh
scripts/release_tests/run_test_pypi_odmltools.sh
setup.py
test/test_rdf_reader.py
test/test_rdf_writer.py

The rdflib library version upgrade from 5 to 6 introduced breaking changes and dropped support for Python versions < 3.7.
This PR
- updates the relevant codebase of the odml library to work with rdflib version 6+ on default installation with Python versions 3.7+.
- additionally the odml library still supports an installation with Python versions < 3.7 pinning the rdflib version to 5.0.0, but informs on installation and usage that both Python version and rdflib version are outdated, this installation is untested and both Python and rdflib version should be upgraded to a more recent distribution.
- CI tests for Python 3.5 and 3.6 are removed.
- installation tests for Python 3.5 and 3.6 via the `scripts/release_test` scripts are still available and functional to check basic installation and …

rdflib dependency update, preparation release v1.5.3

---

odml/tools/odmlparser.py
odml/tools/xmlparser.py

Since these are not standalone scripts, but modules, they do not
require a shebang.
While packaging for Fedora rpmlint threw an error pointing this
out.

Remove shebang from modules
