G-Node/python-odml

odml/types.py
=> fix dtype to string problem

doc/example_odMLs/thgttg.py
Earlier the example directory used bore a different desktop name. I have generalized it 
Please have a look at the commit.
Will do necessary changes for Linux of desired.
=> generalized the code to save the example xml for any windows desktop

odml/terminology.py, odml/tools/xmlparser.py
Using py2 there will be warning which are related to threading issues
=> [terminology] caching and loading now works for py2/3 back and forth

.travis.yml, odml/__init__.py, setup.py
- A simple implementation of adding a `version` attribute to the project. 
- Also, tried to fix some TravisCI build issues.
Fixes #62
=> Add project version attribute

CONTRIBUTING.md, GSoC.md
Added GSoC contributing document and linked it in the general contribution guide.
=> Update contributing and GSoC documents

doc/example_odMLs/thgttg.py, odml/tools/xmlparser.py
- Update the example odML generation, to reflect the removal of odml.Value class
- Trim the newline character at the end of CSV generated string of Values, before writing it to the `odml` output file.
=> Example odML update

odml/__init__.py, odml/addons.py, odml/base.py, odml/doc.py, odml/dtypes.py, odml/format.py, odml/property.py, odml/section.py, odml/terminology.py, odml/tools/doc_inherit.py, odml/tools/dumper.py, odml/tools/jsonparser.py, odml/tools/xmlparser.py, odml/validation.py, setup.py, test/test_bugs.py, test/test_dtypes.py, test/test_find_section.py, test/test_infer_type.py, test/test_iterators.py, test/test_links.py, test/test_mdoc.py, test/test_mdoc_property_add.py, test/test_msec.py, test/test_property.py, test/test_samplefile.py, test/test_section.py, test/test_validation.py
A general (and quick) fix for most of the line length errors and whitespace usages in the codebase.
This is not much necessary at this stage but will definitely be helpful.
Though some long lines of code have lost readability, they will be fixed more elegantly as and when I come across them.  :)
=> [PEP8] Fix line length errors and whitespace issues 

.gitignore, doc/example_odMLs/THGTTG.odml, odml/dtypes.py, odml/tools/__init__.py, odml/tools/xmlparser.py, test/test_addons.py, test/test_dtypes.py, test/test_dumper.py
This PR includes :- 
- Addition of a few **unit tests**, and some placeholder tests
- **Cleaning** up of **unused code** segments to increase coverage
- A few **changes** in some **logics in DType** handling
Wherever there is a change, I have tried to explain it in a `CHANGE - WHY` blocks kind of thing, so that       you can know the purpose of the change, and can check more easily whether the changes are desired or not.  :sweat_smile: 
P.S. :- If the changes are approved, do not merge the PR right away. I'll clean up the `CHANGE - WHY` bocks. They'll look odd in the codebase.
=> Add unit tests; Clean redundant code

doc/example_odMLs/THGTTG.odml, doc/example_odMLs/ex_1.odml, doc/example_odMLs/ex_1.rdf, doc/example_odMLs/ex_2.odml, doc/example_odMLs/odml_ex_1_generator.py, odml/tools/__init__.py, odml/tools/rdf_converter.py
This PR includes:
1. Adding the RDFWriter class for the odml-rdf conversion.
2. Some example files used for the manual testing.
3. Updates to the THGTTG.odml (ids).
=> [rdf] Add odml-rdf converter

test/test_rdf_writer.py
This PR includes unit tests for the RDFWriter class.
=> [rdf] Add tests for the RDFWriter class

odml/format.py, odml/property.py, test/test_property.py
Implementation of the Property.value_origin due to #130
=> Add value_origin to the Property entity

doc/example_rdfs/example_data/2010-04-16-ab_cutoff_300_contrast_20%.ttl, doc/example_rdfs/sparql_example_queries.py
This PR includes:
- Example script with example sparql queries using rdflib.plugins.sparql.
- Converted to turtle format test data file from gin-odml repository.
close #142 #148
=> Sparql example script and data

README.rst, odml/tools/__init__.py
- Change Python version to **2.7+** and **3.4+**
- Add **yaml** installation instructions
- Change **enum** to **enum34** ([Why ?](https://stackoverflow.com/a/21715170))
- Add import for modules in odml/tools to odml/tools/\_\_init\_\_.py
=> [1.3] Update README for dependencies

odml/format.py, odml/tools/odmlparser.py, odml/tools/rdf_converter.py
This PR includes:
- RDFReader class for conversion rdf files to odml #149.
- Relevant extension to `odmlparser.py` to support generic conversion that can be called from the module.
- Bug fix for python 3 version in `format.revmap()`
=> RDF-odml converter

odml/section.py, odml/terminology.py, test/test_terminology.py
this pr is meant as a basis for discussion, not finished yet, it tackles issues #134 #131 
@lzehl please have a look...
=> Extensions to the terminology handling

odml/tools/__init__.py, odml/tools/version_converter.py
Moving the odML version converter from the current dev-odml-rdf branch to master.
=> odML version converter

odml/fileio.py, odml/tools/xmlparser.py, test/test_dumper.py
* fixes issue #176 
* adds a proper error message when trying to open a non-existing file
* appends a file extension to filename, if not given. This restricts the available file extensions to .xml .json, .yaml. Which I personally like, but we can discuss this
=> removes brackets from single value csv, plus some more

doc/RDF_tools_benchmarking.ipynb
This PR has:
- Jupyter notebook with extended documentation, consisting sparql benchmarking.
=> Add extended version of RDF documentation with sparql benchmarking

odml/property.py, test/test_property.py, test/test_rdf_writer.py
=> Limit uncertainty to float

README.md, doc/tutorial.rst, docs/index.md, odml/info.json
This PR
- updates the tutorial with a couple of typo fixes and additional description about load/save specifics.
- adds a nix-odml-converter command line script description to the odML project page.
=> Project page and tutorial updates

.travis.yml, appveyor.yml, odml/base.py, odml/doc.py, odml/dtypes.py, odml/fileio.py, odml/format.py, odml/property.py, odml/rdf/fuzzy_finder.py, odml/rdf/query_creator.py, odml/section.py, odml/templates.py, odml/terminology.py, odml/tools/converters/format_converter.py, odml/tools/converters/version_converter.py, odml/tools/dict_parser.py, odml/tools/doc_inherit.py, odml/tools/dumper.py, odml/tools/odmlparser.py, odml/tools/version_converter.py, odml/tools/xmlparser.py, odml/validation.py, test/test_dumper.py, test/test_links.py, test/test_samplefile.py
This PR tries to cleanup all minor PEP8 issues in one go. It addresses only issues that do not change any behaviour. From my point of view any future PRs addressing code quality will be easier to review and discuss if they are not mixed with additional minor PEP8 issues.
The PR further tries to now provide full documentation for all relevant classes and functions.
The PR also updates the CI builds to include Python 3.8 on all OS and adds an allowed to fail build for Python 3.9dev on Travis.
=> General cleanup

appveyor.yml
... since python setup.py test is deprecated.
=> [appveyor] Use pytest
